services:
    app:
        container_name: wishlist-app
        build:
            context: .
            dockerfile: Dockerfile
        image: wishlist-local
        ports:
            - 3280:3280
        volumes:
            - ${UPLOADS_VOLUME:-./uploads}:/usr/src/app/uploads
            - ${DATA_VOLUME:-./data}:/usr/src/app/data
        env_file:
            - .env
